BEGIN;

-- Supprimer les tables si elles existent déjà pour éviter les conflits
-- CASCADE; signifie que non seulement la table "Users" sera supprimée, mais aussi toutes les dépendances de cette table, assurant une suppression complète et évitant les erreurs de contrainte de clé étrangère ou de dépendances d'objets
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Appointments" CASCADE;
DROP TABLE IF EXISTS "Comments" CASCADE;

-- Création de la table Users
CREATE TABLE "Users" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    postalcode TEXT NOT NULL,
    phone INTEGER NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL

);

-- Création de la table Appointments
CREATE TABLE "Appointments" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    date TEXT,
    hour TEXT,
    details TEXT,
    users_id INTEGER REFERENCES "Users"("id") ON DELETE CASCADE
    -- ON DELETE CASCADE fait en sorte que les enregistrements liés sont également supprimés lorsque le parent est supprimé

);

-- Création de la table Comments
CREATE TABLE "Comments" (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT,
    users_id INTEGER REFERENCES "Users"("id") ON DELETE CASCADE
    -- ON DELETE CASCADE fait en sorte que les enregistrements liés sont également supprimés lorsque le parent est supprimé
);

COMMIT;