BEGIN;

-- Supprimer les tables si elles existent déjà pour éviter les conflits
-- CASCADE; signifie que non seulement la table "Customer" sera supprimée, mais aussi toutes les dépendances de cette table, assurant une suppression complète et évitant les erreurs de contrainte de clé étrangère ou de dépendances d'objets
DROP TABLE IF EXISTS "Customers" CASCADE;
DROP TABLE IF EXISTS "Appointments" CASCADE;
DROP TABLE IF EXISTS "Comments" CASCADE;

-- Création de la table Customers
CREATE TABLE "Customers" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    firstname TEXT,
    lastname TEXT,
    address TEXT,
    phone INTEGER,
    email TEXT UNIQUE,
    password TEXT

);

-- Création de la table Appointments
CREATE TABLE "Appointments" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    date TEXT,
    hour TEXT,
    details TEXT,
    customers_id INTEGER REFERENCES "Customers"("id") ON DELETE CASCADE
    -- ON DELETE CASCADE fait en sorte que les enregistrements liés sont également supprimés lorsque le parent est supprimé

);

-- Création de la table Comments
CREATE TABLE "Comments" (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT,
    customers_id INTEGER REFERENCES "Customers"("id") ON DELETE CASCADE
    -- ON DELETE CASCADE fait en sorte que les enregistrements liés sont également supprimés lorsque le parent est supprimé
);

COMMIT;